# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview

checkoutLocation: "go/src/github.com/cymo-eu/pubsub-firestore-sink"
workspaceLocation: "go/src/github.com/cymo-eu/pubsub-firestore-sink"

tasks:
  - init: >
      go build -o app
    command: >
      ./app
github:
  prebuilds:
    pullRequestsFromForks: true
vscode:
  extensions:
    - golang.go
